### ISSUE TITLE
Expand Test Coverage

### ISSUE THREAD

**Issue by MuxN4** [MuxN4/gocheerio#4]
**Description:**  
Improve testing to ensure library reliability and performance.

**Test Focus Areas:**
- Selector parsing accuracy.
- DOM traversal methods and their reliability.
- Attribute manipulation and handling edge cases.
- Error handling and unexpected input scenarios.

**Comment by lukaszwisniewski88** [comment]
Hello, 
I think it is generally fine idea. so decided to fork the repo and work on this issue. 

just started expanding coverage on attribute matcher 
[matcher_test.go](https://github.com/lukaszwisniewski88/gocheerio/blob/tests/expand-coverage/internal/selector/matcher_test.go)

**Comment by MuxN4** [comment]
Thanks for contributing, glad to hear you’re working on attribute matcher tests. Feel free to reach out if you need any clarifications or guidance. Looking forward to your PR

**Comment by MuxN4** [comment]
Closing this issue as test coverage has been significantly improved via PR #7. A separate issue will be created to address combinator functionality.
